version: "3.7"

services:
    app_proxy:
        environment:
            APP_HOST: bitcoin-tax-calculator_web_1
            APP_PORT: 3123

    web:
        image: onesandzerosnz/bitcoin-tax:latest
        restart: on-failure
        stop_grace_period: 1m
        volumes:
            - ${APP_DATA_DIR}/data:/app/prisma/data
        environment:
            DATABASE_URL: "file:./data/bitcoin_tax.db"
            LOGIN_PASSWORD: ${APP_PASSWORD}
            PORT: "3123"
            HOSTNAME: "0.0.0.0"
            NODE_ENV: "production"
